import React,{ useState } from 'react'
import { getDatabase, ref, set, push } from "firebase/database";
import './LoginRegister';
import { initializeApp } from 'firebase/app';
import { firebaseConfig } from '../../FirebaseConfig';


const LoginRegister = () => {
    // These states hold the text the user types
    // This component allows users to input data
    let [Email, setEmail] = useState("")
    let [Password, setPassword] = useState("")

    // This function saves the input data to the Firebase Realtime Database under 
    // the "drivers" node. Each entry is stored as a new document with a unique key generated by push().
  
    const handleSubmit = async (e) => {
      // Initialize Firebase
        const app = initializeApp(firebaseConfig);
        const db = getDatabase(app);
        const newDocRef = push(ref(db, 'drivers'));
        // The set() function is used to write the data to the database. 
        // It takes the reference to the new document and an object containing the data to be saved.
        set(newDocRef, {
          email: Email,
          password: Password
        }).then(() => {
          alert("Data saved successfully!");
        }).catch((e) => {
          alert(`Failed to save data: ${e.message}`);
      });
      e.preventDefault(); // Prevents the page from refreshing
      console.log("Login Attempt:", { Email, Password });
      alert(`Logged in with: ${Email}`);
  }

  return (
    <div className="login-container">
      <form className="login-form" onSubmit={handleSubmit}>
        <h2>Welcome Back</h2>
        <p>Please enter your details</p>

        <div className="input-group">
          <label>Email</label>
          <input 
            type="email" 
            placeholder="email@example.com" 
            value={Email}
            onChange={(e) => setEmail(e.target.value)}
            required 
          />
        </div>

        <div className="input-group">
          <label>Password</label>
          <input 
            type="password" 
            placeholder="••••••••" 
            value={Password}
            onChange={(e) => setPassword(e.target.value)}
            required 
          />
        </div><br />

        <button onClick={handleSubmit} type='submit' className="login-button">Sign In</button>
        
        <p className="signup-link">
          Don't have an account? <a href="Register">Sign up</a>
        </p>
      </form>
    </div>
  )  
}

export default LoginRegister