import React,{ useState } from 'react'
import { getDatabase, ref, set, push } from "firebase/database";
import './LoginRegister';
import { initializeApp } from 'firebase/app';
import { firebaseConfig } from '../../FirebaseConfig';
import { auth, db } from '../../FirebaseConfig';
import {z} from "zod";
import {useForm} from "react-hook-form";
import {zodResolver} from "@hookform/resolvers/zod";
import { createUserWithEmailAndPassword } from 'firebase/auth';
import { doc, setDoc, serverTimestamp } from 'firebase/firestore';


const Register = () => {
    // These states hold the text the user types
    // This component allows users to input data
    let [Email, setEmail] = useState("")
    let [Password, setPassword] = useState("")
    let [Name, setName] = useState("")
    let [Surname, setSurname] = useState("")

    // This function saves the input data to the Firebase Realtime Database under 
    // the "drivers" node. Each entry is stored as a new document with a unique key generated by push().
  
    const handleSubmit = async (e) => {
      // Initialize Firebase
        const app = initializeApp(firebaseConfig);
        const db = getDatabase(app);
        const newDocRef = push(ref(db, 'drivers'));
        // The set() function is used to write the data to the database. 
        // It takes the reference to the new document and an object containing the data to be saved.
        set(newDocRef, {
          email: Email,
          password: Password,
          name: Name,
          surname: Surname
        }).then(() => {
          alert("Data saved successfully!");
        }).catch((e) => {
          alert(`Failed to save data: ${e.message}`);
      });
      e.preventDefault(); // Prevents the page from refreshing
      console.log("Registration Attempt:", { Email, Password, Name, Surname });
      alert(`Registered with: ${Email}`);
  }

  return (
    <div className="login-container">
      <form className="login-form" onSubmit={handleSubmit}>
        <h2>Create Account</h2>
        <p>Please enter your details</p>

        <div className="input-group">
          <label>Email</label>
          <input 
            type="email" 
            placeholder="email@example.com" 
            value={Email}
            onChange={(e) => setEmail(e.target.value)}
            required 
          />
        </div>

        <div className="input-group">
          <label>Password</label>
          <input 
            type="password" 
            placeholder="••••••••" 
            value={Password}
            onChange={(e) => setPassword(e.target.value)}
            required 
          />
        </div>
        <div className="input-group">
          <label>Name</label>
          <input 
            type="text" 
            placeholder="John" 
            value={Name}
            onChange={(e) => setName(e.target.value)}
            required 
          />
        </div>
        <div className="input-group">
          <label>Surname</label>
          <input 
            type="text" 
            placeholder="Doe" 
            value={Surname}
            onChange={(e) => setSurname(e.target.value)}
            required 
          />
        </div>
        <br />

        <button onClick={handleSubmit} type='submit' className="login-button">Sign Up</button>
        
        <p className="signup-link">
          Already have an account? <a href="Login">Log in</a>
        </p>
      </form>
    </div>
  )  
}

export default Register