import React, {useState} from 'react'
import app from "../FirebaseConfig"
import { getDatabase, ref, set, push } from "firebase/database";

/// This component allows users to input data 
const Write = () => {
    let [inputValue1, setinputValue1] = useState("")
    let[inputValue2, setInputValue2] = useState("")

    // This function saves the input data to the Firebase Realtime Database under 
    // the "drivers" node. Each entry is stored as a new document with a unique key generated by push().
    const  saveData = async () => {
        const db = getDatabase(app);
        const newDocRef = push(ref(db, 'drivers'));
        // The set() function is used to write the data to the database. 
        // It takes the reference to the new document and an object containing the data to be saved.
        set(newDocRef, {
          email: inputValue1,
          fullname: inputValue2
        }).then(() => {//this is like a try catch block, if the data is saved successfully, it will show an alert message. If there is an error, it will catch the error and display an alert with the error message.
          alert("Data saved successfully!");
        }).catch((error) => {
          alert("Failed to save data: " + error.message);
        });
    }

  return (
    <div>
        <input type="text" value={inputValue1} onChange={(e) => setinputValue1(e.target.value)} />
        <input type="text" value={inputValue2} onChange={(e) => setInputValue2(e.target.value)} /><br />
        <button onClick={saveData}>SAVE DATA</button>
    </div>  
  )
}

export default Write